language: shell

services:
  - docker

before_install:
  - docker pull "$distro":latest
  - docker run -v $PWD:/src "$distro":latest /bin/bash -c "$install && gem install bundler --no-document --no-format-executable && cd /src && bundle install && distro=$distro bundle exec rspec --tag docker"

env:
  - distro=archlinux install='pacman -Sy --noconfirm base-devel ruby && PATH="$PATH:$(ruby -e "puts Gem.user_dir")/bin"'
  - distro=debian install="apt-get update; apt-get install -y build-essential ruby ruby-dev"
  - distro=fedora install='dnf install -y gcc-c++ make redhat-rpm-config ruby ruby-devel'
  - distro=linuxmintd/mint19.3-amd64 install="apt-get update; apt-get install -y build-essential ruby ruby-dev"
  - distro=manjarolinux/base install='pacman -Sy --noconfirm base-devel ruby && PATH="$PATH:$(ruby -e "puts Gem.user_dir")/bin"'
  - distro=opensuse/leap install='zypper install -y gcc-c++ make ruby ruby-devel'
  - distro=opensuse/tumbleweed install='zypper install -y gcc-c++ make ruby ruby-devel'
  - distro=ubuntu install="apt-get update; apt-get install -y build-essential ruby ruby-dev"

jobs:
  include:
    - &shared
      language: ruby
      rvm: ruby # Latest stable version
      script: bundle exec rspec --tag ~docker # Don't run specs with docker: true
      cache: bundler
      # Clear out values that were set above specifically for docker runs
      env:
      before_install:
      services:
    - <<: *shared
      os: linux
    - <<: *shared
      os: osx
